---
- hosts: bmscp
  gather_facts: no

  tasks:
    - name: register TMGI from BM-SC access log
      shell: egrep -wo '0x\w{12}' /var/vendor/bm-sc/control_plane/log/access.log|cut -c 3- | uniq
      register: result

    - name: iterate through TMGIs in result and segregate access messages for each TMGI
      shell:
        cmd: |
          echo '                                                       ' >> bmscaccess.txt
          echo '********************tmgi={{ item }}********************' >> bmscaccess.txt
          echo '                                                       ' >> bmscaccess.txt
          cat /var/vendor/bm-sc/control_plane/log/access.log |grep {{ item }} >> bmscaccess.txt
      with_items: "{{ result.stdout_lines }}"
